[phases.setup]
nixPkgs = ['nodejs_20', 'corepack', 'chromium']

[phases.install]
cmds = [
  'corepack enable',
  'export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true',
  'pnpm install'
]

[phases.build] 
cmds = ['pnpm build']

[start]
cmd = 'pnpm start'

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
PUPPETEER_EXECUTABLE_PATH = '/nix/store/*/bin/chromium'
