[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'python311Packages.virtualenv']

[phases.install]
cmds = [
  'python -m venv /opt/venv',
  '/opt/venv/bin/pip install -r requirements.txt'
]

[phases.build]
cmds = ['python -c "import sys; print(sys.version)"']

[start]
cmd = '/opt/venv/bin/python server.py'

[variables]
PYTHONUNBUFFERED = '1'
PATH = '/opt/venv/bin:$PATH'
