[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']

[phases.install]
cmds = [
  'pip install -r requirements.txt'
]

[phases.build]
cmds = ['python -c "import sys; print(sys.version)"']

[start]
cmd = 'python server.py'

[variables]
PYTHONUNBUFFERED = '1'
